config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home', as: 'home'
  resources :gossips do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :gossip
  has_many :likes
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user, optional: true
  has_and_belongs_to_many :tags
  has_many :comments
  has_many :likes
end

app/models/like.rb
class Like < ApplicationRecord

end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: 'User'
  belongs_to :recipient, class_name: 'User'
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_and_belongs_to_many :gossips
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips
  has_many :comments
  has_many :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


  def new
    # On instancie un nouveau comment
    @comment = Comment.new
  end

  def create
  # On passe les params du formulaire pour creer un nouveau comment
  @comment = Comment.new(anonymous_commentor: comment_params[:anonymous_commentor],content: comment_params[:content])

  #finding the appropriate Gossip

  @gossip = Gossip.find(params[:gossip_id])

  @comment.user_id = 1

  @gossip.comments << @comment

  if @gossip.save && @comment.save

    #@comment = Gossip.comments.create(
    #  content: params[:comment][:content],
    #   anonymous_gossiper: params[:comment][:anonymous_commentor]
    #   content: params[:comment][:gossip_id]
     #)
    # On renvoie vers la page du gossip
    redirect_to '/'''
  end
end

private

def comment_params
  params.require(:comment).permit(:anonymous_commentor, :content, :gossip_id)
end

end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController


  def index
    @gossip = Gossip.all
    puts 'j affiche depuis index'
  end

  def new
    puts "j'affiche depuis new"
    @gossip = Gossip.new
    puts params.inspect
  end

  def create
    gossip = Gossip.create(gossip_params)



    puts 'j affiche depuis create'
    #redirect_to action: 'show', id: @gossip.title
    redirect_to gossip_path(gossip.id)
  end


  def show
    puts "j'affiche depuis show"
    @gossip = Gossip.find(params[:id])
    @comment = @gossip.comments.build
  end

  def edit
    puts "j'affiche depuis edit"
    @gossip = Gossip.find(params[:id])
  end

  def update
    gossip = Gossip.create(gossip_params)
    redirect_to gossip_path(gossip.id)
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to gossips_path
  end

  private

  def gossip_params
    params.require(:gossip).permit(:title, :content, :anonymous_gossiper)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/gossisp_helper.rb
module GossispHelper
end

app/helpers/static_pages_controller_helper.rb
module StaticPagesControllerHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/comments/new.html.erb
<h1>Ajout commentaire</h1>


<%= form_for @comment, url: {action: "create"} do |f| %>
<div class="form-group">
  <label>Ton nom anonyme:</label>
  <%= f.text_field :anonymous_commentor, class: 'form-control', placeholder: 'ton pseudo' %>
</div>
<div class="form-group">
  <label>Contenu du commentaire: </label>
    <%= f.text_field :content, class: 'form-control', placeholder: 'ton commentaire' %>
  </div>
 <%= f.submit  %>
 <% end -%>

app/views/gossips/edit.html.erb
<h1>Editer un Gossip:</h1>

<%= form_for @gossip do |f| %>
  <div class="form-group">
    <label>Nom du Gossip: </label>
      <%= f.text_field :title, class: 'form-control', placeholder: 'title' %>
    </div>
    <div class="form-group">
      <label>Quel est ton gossip? </label>
        <%= f.text_area :content, class: 'form-control', placeholder: 'ton gossip' %>
    </div>
    <div class="form-group">
      <label>Ton nom nom anonyme:</label>
      <%= f.text_field :anonymous_gossiper, class: 'form-control', placeholder: 'ton pseudo' %>
    </div>
    <div>
      <button type="submit" class="btn btn-primary">Valider</button>
    </div>
 <% end -%>

app/views/gossips/index.html.erb
<h1>Voici la liste des Gossips</h1>

<div class="container">
  <table >
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>Pseudo</th>
    <th>Action</th>
    <th>Visualiser</th>

  </tr>
  </table>
  <% @gossip.each do |gossip| %>
  <table >
    <tr>
      <td><%= gossip.title %></td>
      <td><%= gossip.content %></td>
      <td><%= gossip.anonymous_gossiper %></td>
      <td><%= link_to 'Supprimer', gossip, method: :delete %></td>
      <td><%= link_to 'Visualiser', gossip_path(gossip) %></td>
    </tr>

  </table>
  <% end %>
</div>


<div class='container'>
  <a href="<%= new_gossip_path %>" class= 'btn btn-warning'>Créer</a>
</div>

app/views/gossips/new.html.erb
<h1>Création d'un nouveau Gossip</h1>

<%= form_for @gossip do |f| %>
  <div class="form-group">
    <label>Nom du Gossip: </label>
      <%= f.text_field :title, class: 'form-control', placeholder: 'title' %>
    </div>
    <div class="form-group">
      <label>Quel est ton gossip? </label>
        <%= f.text_area :content, class: 'form-control', placeholder: 'ton gossip' %>
    </div>
    <div class="form-group">
      <label>Ton nom nom anonyme:</label>
      <%= f.text_field :anonymous_gossiper, class: 'form-control', placeholder: 'ton pseudo' %>
    </div>
    <div>
      <button type="submit" class="btn btn-primary">Valider</button>
    </div>
 <% end -%>

app/views/gossips/show.html.erb
<h1>Ton Gossip: <%= @gossip.title %></h1>

<div class='container'>
  <p>  content : <%= @gossip.content %>  </p>
  <p>  author : <%= @gossip.anonymous_gossiper %>  </p>
</div>

<div class='container'>
  <a href="<%= edit_gossip_path(@gossip.id) %>" class= 'btn btn-warning'>Editer</a>
  <a href="<%= gossips_path %>" class= 'btn btn-primary'>Revenir à l index</a>
  <a href="<%= gossip_path(@gossip)%>" class='btn btn-danger' data-confirm='sure' data-method='DELETE'>Supprimer</a>
</div>



<h1>
  <%= link_to 'Ajout commentaire', new_gossip_comment_path(@gossip.id)  %>
</h1>

<h2>Comments</h2>

<% @gossip.comments.each do |l|  %>

<%= l.content %> by <%= l.anonymous_commentor %>
<br>
<% end %>

app/views/layouts/_header.html.erb
<div class="container">
<header class="navbar navbar-fixed-top navbar-inverse">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" <%= link_to "Accueil", home_path %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link" <%= link_to "Index des gossips", gossips_path %></li></a>
      <a class="nav-item nav-link disabled" <%= link_to "Nouveau gossip", new_gossip_path %></a>
    </div>
  </nav>
  </div>
</header>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThpWeek5Thehackinggossip</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Bienvenue !</h1>
  <h3>
    Ici, tu peux retrouver les moussaillons 🎓
  </h3>
  <%= link_to "Enregistre-toi !", '#', class: "btn btn-lg btn-primary" %>
</div>
<p>© 2018, Made with ❤️ in Rennes</p>

app/views/static_pages/new.html.erb
<h1>Création d'un nouveau Gossip</h1>

<%= form_for @gossip do |f| %>
  <div class="form-group">
    <label>Nom du Gossip: </label>
      <%= f.text_field :title, class="form-control" %>
    </div>
    <div class="form-group">
      <label>Quel est ton gossip? </label>
        <%= f.text_aera :content, class="form-control" %>
    </div>
    <div class="form-group">
      <label>Ton nom nom anonyme:</label>
      <%= f.text_field :anonymous_gossiper, class ="form-control" %>
    </div>
    <div>
      <button type="submit" class="btn btn-primary">
    </div>
 <% end -%>